### ISSUE TITLE
RowProxy and ResultProxy in sqlalchemy

### ISSUE THREAD

**Issue by wknds** [tulir/mautrix-python#46]
Starting with sqlalchemy version 1.4.0, RowProxy and ResultProxy are handled differently [(changelog)](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#change-4710-core), giving me the following error when I generate the appservice registration within mautrix_telegram:

```
$ python -m mautrix_telegram -g -c config.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/__main__.py", line 22, in <module>
    from mautrix.util.db import Base
  File "/home/user/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/__init__.py", line 1, in <module>
    from .base import Base, BaseClass
  File "/home/user/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 11, in <module>
    from sqlalchemy.engine.result import RowProxy, ResultProxy
ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine.result' (/home/user/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/result.py)
```

**Comment by tulir** [comment]
mautrix-telegram was already changed to require SQLAlchemy<1.4. I'll probably drop support for sqlite entirely in the near future though

**Comment by TanmayAT** [comment]
for pickle file data loading it gaves same error how to counter it
