### ISSUE TITLE
get_message method from mautrix.client.api.events throws error

### ISSUE THREAD

**Issue by subiol** [tulir/mautrix-python#47]
I am calling the method get_messages from mautrix.client.api.events this way:

`messages = await self.client.get_messages (room_id, PaginationDirection.BACKWARD, last_sync_token, limit=limit)`

I have logged the variables just before calling the method and all seem to have correct values. I have also tried getting the sync token, by getting the prev_batch per each room, or getting it from next_bact in general. Same result with any.

This is the traceback I am getting:
```
redact_user_in_room, last_sync_token:  s2892556_34809279_8447_1820949_129088_661_35983_822932_13 , room_id:  !oQDevAXVfxcPZfmIYe:monero.social , limit:  30
[2021-05-24 09:40:24,415] [ERROR@maubot.client.@banhammertesting:monero.social] Failed to run handler
Traceback (most recent call last):
  File "/home/maubot/maubot/lib/python3.7/site-packages/mautrix/client/syncer.py", line 200, in _catch_errors
    await handler(data)
  File "/home/maubot/maubot/plugins/com.baldasano.antifuk-v0.2.0-ts1621838390.mbp/antifuk/bot.py", line 58, in event_message_handler
    await self.control_room.process_message (evt)
  File "/home/maubot/maubot/plugins/com.baldasano.antifuk-v0.2.0-ts1621838390.mbp/antifuk/control_room.py", line 738, in process_message
    await self._redact (evt, message_bits)
  File "/home/maubot/maubot/plugins/com.baldasano.antifuk-v0.2.0-ts1621838390.mbp/antifuk/control_room.py", line 507, in _redact
    await self.bot.redact_user_in_room (room_id, user_id, limit=messages_limit, log=self.log)
  File "/home/maubot/maubot/plugins/com.baldasano.antifuk-v0.2.0-ts1621838390.mbp/antifuk/plugin_extra.py", line 238, in redact_user_in_room
    messages = await self.client.get_messages (room_id, PaginationDirection.BACKWARD, last_sync_token, limit=limit)
  File "/home/maubot/maubot/lib/python3.7/site-packages/mautrix/client/api/events.py", line 240, in get_messages
    query_params=query_params)
  File "/home/maubot/maubot/lib/python3.7/site-packages/mautrix/api.py", line 254, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/home/maubot/maubot/lib/python3.7/site-packages/mautrix/api.py", line 168, in _send
    async with request as response:
  File "/home/maubot/maubot/lib/python3.7/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/maubot/maubot/lib/python3.7/site-packages/aiohttp/client.py", line 513, in _request
    traces=traces,
  File "/home/maubot/maubot/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 283, in __init__
    url2 = url.with_query(params)
  File "/home/maubot/maubot/lib/python3.7/site-packages/yarl/_url.py", line 983, in with_query
    new_query = self._get_str_query(*args, **kwargs)
  File "/home/maubot/maubot/lib/python3.7/site-packages/yarl/_url.py", line 944, in _get_str_query
    query = "&".join(self._query_seq_pairs(quoter, query.items()))
  File "/home/maubot/maubot/lib/python3.7/site-packages/yarl/_url.py", line 907, in _query_seq_pairs
    yield quoter(key) + "=" + quoter(cls._query_var(val))
  File "/home/maubot/maubot/lib/python3.7/site-packages/yarl/_url.py", line 925, in _query_var
    "of type {}".format(v, cls)
TypeError: Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>
```

I am fullfilling all the mandatory parts of the method plus an optional one (limit). Is there something I am missing in calling the method or is this a bug of mautrix?

**Comment by subiol** [comment]
I was running mautrix 0.9.2 from pypi. After installing from last git, the problem is gone.
